server:
  port: 8080
  servlet:
    context-path: /weibo-bot

spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    cache: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weibo_bot?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: hzhssg123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 120.78.148.229
    port: 6379
    password: RedisHanrAx123

logging:
  config: classpath:log4j2-spring.xml
